env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
parserOptions:
  ecmaVersion: 12
plugins:
  - vue
rules:
  curly: warn
  semi-spacing:
    - error
    - before: false
      after: true
  space-before-blocks:
    - warn
    - functions: always
